/**
 * 离线降级知识包：团队自写的摘要内容，不包含《机器人产品内参》原文。
 * 完整知识库通过云端 knowledgePack 私有接口下发；断网或未登录云环境时，
 * 学习伙伴与挑战评估使用这份摘要兜底，并在界面上明确标注离线模式。
 */
export const FALLBACK_KNOWLEDGE_PACK: unknown = {
  manifest: {
    name: "身知回响离线知识摘要",
    version: "offline-summary-2026-08-05",
    sourceType: "curated-offline-summary",
    documentCount: 8,
    chunkCount: 8,
    generatedOn: "2026-08-05",
    notice: "离线模式下的自写摘要；联网后可获得完整知识库。",
  },
  chunks: [
    {
      id: "offline-perception-overview",
      documentId: "offline-perception",
      title: "感知系统",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 1,
      tags: ["perception", "sensor-selection"],
      text: "感知系统是机器人理解环境的入口，常见组合包括激光雷达、深度相机、超声波与碰撞条。做产品选型时先看任务需要什么信息：测距、语义识别还是接近预警，再决定传感器组合，而不是先选最贵的方案。任何单一传感器都有失效条件，安全相关场景必须保留冗余。",
    },
    {
      id: "offline-lidar",
      documentId: "offline-perception",
      title: "激光雷达",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 2,
      tags: ["perception", "sensor-selection"],
      text: "激光雷达通过激光测距生成点云，能稳定获取障碍物的距离与轮廓，不依赖环境光照，所以夜间仓库、黑暗走廊里依然可以避障与建图。它的边界是成本较高、对雨雪和强反光表面敏感，且不擅长理解语义，例如分不清行人与纸箱，通常需要相机补充。",
    },
    {
      id: "offline-depth-camera",
      documentId: "offline-perception",
      title: "深度相机",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 3,
      tags: ["perception", "sensor-selection"],
      text: "深度相机同时提供图像与距离信息，能识别人、货架和障碍物类别，成本低于激光雷达。但它依赖光照条件，强光、暗光、反光和透明材质都会让深度数据变差。在人员混行的仓库里，深度相机适合做人机识别与辅助避障，不宜单独承担安全职责。",
    },
    {
      id: "offline-warehouse-safety",
      documentId: "offline-warehouse",
      title: "仓储物流机器人",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 4,
      tags: ["warehouse", "perception", "sensor-selection"],
      text: "仓储物流机器人在人机混行环境中工作，安全是硬约束：通道窄、货架遮挡、人员随机出现。行业常见做法是多重防护：激光雷达负责远距离避障，碰撞条与安全触边负责近端兜底，视觉负责识别人员与货物状态，任何一层失效都有下一层承接。",
    },
    {
      id: "offline-visual-avoidance",
      documentId: "offline-warehouse",
      title: "视觉避障",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 5,
      tags: ["warehouse", "perception"],
      text: "视觉避障依赖相机与算法识别障碍物，优势是能理解语义、成本可控；劣势是受光照、反光与遮挡影响大。夜间或反光地面场景中视觉可靠性会下降，所以安全相关避障不能只靠视觉，需要测距类传感器与物理防护作为冗余。",
    },
    {
      id: "offline-safety-redundancy",
      documentId: "offline-safety",
      title: "安全防护",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 6,
      tags: ["warehouse", "perception", "product"],
      text: "安全防护设计的核心是假设每一层都会失效：传感器可能被遮挡，算法可能误判，通信可能延迟。因此把防护分层：远端感知减速、近端急停、物理缓冲，并要求失效时进入安全状态。评估方案时先问失效后果，再问哪一层负责承接。",
    },
    {
      id: "offline-selection",
      documentId: "offline-product",
      title: "产品选型",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 7,
      tags: ["product", "sensor-selection"],
      text: "传感器与能力选型建议按场景约束、任务要求、能力组合、失效边界、成本验证的顺序展开。先写清环境与任务，再组合能力，最后检查失效边界和成本，并用真实场景测试验证，而不是只看单项参数或追逐最新方案。",
    },
    {
      id: "offline-validation",
      documentId: "offline-product",
      title: "验证与数据",
      sourceFile: "离线摘要",
      sourceType: "curated-offline-summary",
      order: 8,
      tags: ["product", "warehouse"],
      text: "判断一批数据或一项能力是否真正提升了机器人，要看任务结果：避障成功率、急停次数、人工接管率、单位时间处理量。上线前在真实或仿真场景中覆盖光照变化、遮挡、反光与人机混行等边界条件，把失效案例变成下一轮迭代的输入。",
    },
  ],
};
